language: python
python:
  - "2.7.12"

env:
  - DJANGO="django==1.7"
  - DJANGO="django==1.8"
  - DJANGO="django==1.9"
  - DJANGO="django==1.10"

install:
  - pip install $DJANGO
  - pip install coverage


branches:
  only:
    - master

script:
  - coverage run dajaxice/tests/runtests.py
